server.port=3001

spring.application.name=matchingsystem

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/

internal.token=eqgoodInternalToken

rocketmq.name-server=rmqnamesrv:9876

